### ISSUE TITLE
anagram_finder - incorrect tests

### ISSUE THREAD

**Issue by dyatlov** [Hexlet/battle_asserts#230]
https://github.com/Hexlet/battle_asserts/blob/master/src/battle_asserts/issues/anagram_finder.clj

expected is [["ssol", "ssol"], ["ryucnot", "ryucnot", "tunycro"]]
apply(:solution, arguments) is [["ryucnot", "ryucnot", "tunycro"], ["ssol", "ssol"]]

**Comment by mokevnin** [comment]
fixed. thanks!
