### ISSUE TITLE
array_transpose - should be harder to solve..

### ISSUE THREAD

**Issue by dyatlov** [Hexlet/battle_asserts#231]
In ruby it's just one method:

```ruby
def solution(a)
  a.transpose
end
```

that's not fair comparing to other languages

**Comment by mokevnin** [comment]
Some problems have easy solution (using internal method), that is a feature and not a bug ;)

**Comment by dyatlov** [comment]
I'm not saying it's a bug but use of such "features" would better be avoided. That's not fair when comparing to JS, Java and PHP.
